In [3]:
import requests
import time
import pandas as pd
import random
from tqdm import tqdm

In [ ]:
####### lấy từng trang all sp giày thể thao
import requests
import pandas as pd
import time
import random

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36',
    'Referer': 'https://tiki.vn/giày+sandal/c931',
    'Accept': 'application/json, text/plain, */*',
    'Connection': 'keep-alive',
}

params = {
    'limit': '40',  # Lấy 40 sản phẩm mỗi trang
    'page': '1',
    'include': 'advertisement',
    'aggregations': '2',
    'q': 'giày thể thao',
}

product_data = []
for i in range(1, 5):  # Lấy 20 trang dữ liệu
    params['page'] = str(i)
    response = requests.get('https://tiki.vn/api/v2/products', headers=headers, params=params)

    if response.status_code == 200:
        print(f'Page {i}: Request success!!!')
        json_data = response.json()

        if 'data' in json_data:
            for record in json_data.get('data', []):
                product_data.append({
                    'id': record.get('id'),
                    'name': record.get('name'),
                    'price': record.get('price'),
                    'rating': record.get('rating_average'),
                    'review_count': record.get('review_count'),
                    'brand': record.get('brand', {}).get('name'),
                    'url': f"https://tiki.vn/{record.get('url_path')}",
                })
        else:
            print(f'Page {i}: No data found!')
    else:
        print(f'Page {i}: Request failed with status {response.status_code}')

    time.sleep(random.uniform(3, 10))  # Tránh bị chặn

df = pd.DataFrame(product_data)
df.to_csv('giay_the_thaoID.csv', index=False, encoding='utf-8-sig')
print("Done! Data saved to giay_the_thaoID.csv")

Page 1: Request success!!!
Page 2: Request success!!!
Page 3: Request success!!!
Page 4: Request success!!!
Done! Data saved to giay_the_thaoID.csv

In [ ]:
# lấy giày sandal
import requests
import pandas as pd
import time
import random

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36',
    'Referer': 'https://tiki.vn/',
    'Accept': 'application/json, text/plain, */*',
    'Connection': 'keep-alive',
}

params = {
    'limit': '40',  # Lấy 40 sản phẩm mỗi trang
    'include': 'advertisement',
    'aggregations': '2',
    'q': 'giày sandal',
    'page': '1',  # Trang đầu tiên
}

product_data = []
  # Số trang tối đa cần lấy

for i in range(1, 5):
    params['page'] = str(i)
    response = requests.get('https://tiki.vn/api/v2/products', headers=headers, params=params)

    if response.status_code == 200:
        print(f'Page {i}: Request success!!!')
        json_data = response.json()

        if 'data' in json_data and json_data['data']:
            for record in json_data['data']:
                product_data.append({
                    'id': record.get('id'),
                    'name': record.get('name'),
                    'price': record.get('price'),
                    'rating': record.get('rating_average'),
                    'review_count': record.get('review_count'),
                    'brand': record.get('brand', {}).get('name'),
                    'url': f"https://tiki.vn/{record.get('url_path')}",
                })
        else:
            print(f'Page {i}: No more data available!')
            break  # Dừng nếu không còn dữ liệu

    else:
        print(f'Page {i}: Request failed with status {response.status_code}')
        break  # Thoát vòng lặp nếu lỗi

    time.sleep(random.uniform(3, 8))  # Tránh bị chặn

df = pd.DataFrame(product_data)
df.to_csv('giay_sandalID.csv', index=False, encoding='utf-8-sig')
print("Done! Data saved to giay_sandalID.csv")

Page 1: Request success!!!
Page 2: Request success!!!
Page 3: Request success!!!
Page 4: Request success!!!
Done! Data saved to giay_sandalID.csv

In [29]:
## giày boots
import requests
import pandas as pd
import time
import random

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36',
    'Referer': 'https://tiki.vn/',
    'Accept': 'application/json, text/plain, */*',
    'Connection': 'keep-alive',
}

params = {
    'limit': '40',  # Số lượng sản phẩm mỗi trang
    'include': 'advertisement',
    'aggregations': '2',
    'q': 'boots',  # Từ khóa tìm kiếm
}

product_ids = []

for page in range(1, 6):
    params['page'] = str(page)  # Cập nhật số trang
    response = requests.get('https://tiki.vn/api/v2/products', headers=headers, params=params)

    if response.status_code == 200:
        print(f'Page {page}: Request success!')
        json_data = response.json()

        if 'data' in json_data and json_data['data']:
            for record in json_data['data']:
                product_ids.append({'id': record.get('id')})
        else:
            print(f'Page {page}: No more data available!')
            break  # Dừng nếu không còn dữ liệu

    else:
        print(f'Page {page}: Request failed with status {response.status_code}')
        break  # Thoát vòng lặp nếu lỗi

    time.sleep(random.uniform(3, 8))  # Tránh bị chặn

df = pd.DataFrame(product_ids)
df.to_csv('boots_id.csv', index=False, encoding='utf-8-sig')
print("Done! Data saved to boots_id.csv")

Page 1: Request success!
Page 2: Request success!
Page 3: Request success!
Page 4: Request success!
Page 5: Request success!
Done! Data saved to boots_id.csv

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36',
    'Referer': 'https://tiki.vn/giay-tay-cong-so/c1581',
    'Accept': 'application/json, text/plain, */*',
    'Connection': 'keep-alive',
}

params = {
    'limit': '10',
    'sort': 'top_seller',
    'category': '1581',
    'page': '1',
    'urlKey': 'giay-tay-cong-so',
}

product_id = []
for i in range(1, 21):
    params['page'] = str(i)
    response = requests.get('https://tiki.vn/api/personalish/v1/blocks/listings', headers=headers, params=params)

    if response.status_code == 200:
        print(f'Page {i}: Request success!!!')
        json_data = response.json()
        
        if 'data' in json_data:
            for record in json_data.get('data', []):
                product_id.append({'id': record.get('id')})
        else:
            print(f'Page {i}: No data found!')
    else:
        print(f'Page {i}: Request failed with status {response.status_code}')
    
    time.sleep(random.uniform(3, 10))  # Random delay để tránh bị chặn

df = pd.DataFrame(product_id)
df.to_csv('giayTayID.csv', index=False)
print("Done! Data saved to giayTayID.csv")

Page 1: Request success!!!
Page 2: Request success!!!
Page 3: Request success!!!
Page 4: Request success!!!
Page 5: Request success!!!
Page 6: Request success!!!
Page 7: Request success!!!
Page 8: Request success!!!
Page 9: Request success!!!
Page 10: Request success!!!
Page 11: Request success!!!
Page 12: Request success!!!
Page 13: Request success!!!
Page 14: Request success!!!
Page 15: Request success!!!
Page 16: Request success!!!
Page 17: Request success!!!
Page 18: Request success!!!
Page 19: Request success!!!
Page 20: Request success!!!
Done! Data saved to giayTheThaoNamID.csv

In [ ]:
# Hàm parser dữ liệu sản phẩm
def parser_product(json):
    return {
        'Product_ID': json.get('id'),
        'Product_name': json.get('name'),
        #'breadcrumbs' : json.get('breadcrumbs'),
        'Description': json.get('short_description'),
        'brand_name': json.get('brand', {}).get('name'), 
        
        # 'url_product': json.get('breadcrumbs', [{}])[-1].get('url'),
        # 'image_base_url': json.get('images', [{}])[0].get('base_url'),
        # 'rating_average': json.get('rating_average'),
        # 'review_count': json.get('review_count'),
        # 'quantity_sold': json.get('quantity_sold'),
        'price': json.get('price'),
        
        # 'category': [bc.get('name') for bc in json.get('breadcrumbs', [])[:-1]],
        # 'current_seller': json.get('current_seller', {}).get('name'), 
        # 'inventory_status': json.get('inventory_status'),
        # 'stock_item_qty': json.get('stock_item', {}).get('qty'),
        
        
        # 'review_count': json.get('review_count'),
        # 'order_count': json.get('order_count'),
        # 'is_visible': json.get('is_visible'),
        # 'stock_item_qty': json.get('stock_item', {}).get('qty'),
        # 'stock_item_max_sale_qty': json.get('stock_item', {}).get('max_sale_qty'),
        # 'product_nam    e': json.get('meta_title'),
        # 'brand_id': json.get('brand', {}).get('id'),
        # 'brand_name': json.get('brand', {}).get('name')
    }

# Đọc danh sách ID sản phẩm
df_id = pd.read_csv('boots_id.csv')
p_ids = df_id.id.to_list()
result = []

# Bắt đầu thu thập dữ liệu
for pid in tqdm(p_ids, total=len(p_ids)):
    retries = 3  # Số lần thử lại nếu request thất bại
    while retries > 0:
        response = requests.get(f'https://tiki.vn/api/v2/products/{pid}', headers=headers)

        if response.status_code == 200:
            print(f'Crawl data {pid} success!')
            result.append(parser_product(response.json()))
            break  # Nếu thành công, thoát khỏi vòng lặp retry
        elif response.status_code == 429:
            print(f'Too many requests! Waiting before retrying {pid}...')
            time.sleep(random.uniform(5, 10))  # Chờ ngẫu nhiên để tránh bị chặn
        elif response.status_code == 404:
            print(f'Product {pid} not found (404). Skipping...')
            break  # Không thử lại nếu sản phẩm không tồn tại
        else:
            print(f'Failed to fetch data for {pid}, status code: {response.status_code}')
        retries -= 1
    
    # Chờ ngẫu nhiên giữa các request
    time.sleep(random.uniform(1, 5)) 

# Lưu dữ liệu ra file CSV
df_product = pd.DataFrame(result)
df_product.to_csv('boots.csv', index=False)
print("Done! Data saved to boots.csv")

  0%|          | 0/200 [00:00<?, ?it/s]

Crawl data 216940208 success!

  0%|          | 1/200 [00:03<12:11,  3.68s/it]

Crawl data 208324988 success!

  1%|          | 2/200 [00:07<12:01,  3.65s/it]

Crawl data 274457345 success!

  2%|▏         | 3/200 [00:12<14:06,  4.30s/it]

Crawl data 249967896 success!

  2%|▏         | 4/200 [00:14<11:38,  3.56s/it]

Crawl data 274457393 success!

  2%|▎         | 5/200 [00:19<12:37,  3.88s/it]

Crawl data 207359021 success!

  3%|▎         | 6/200 [00:22<12:16,  3.80s/it]

Crawl data 275270637 success!

  4%|▎         | 7/200 [00:26<11:48,  3.67s/it]

Crawl data 249935663 success!

  4%|▍         | 8/200 [00:29<11:20,  3.55s/it]

Crawl data 262058064 success!

  4%|▍         | 9/200 [00:32<10:14,  3.22s/it]

Crawl data 249970641 success!

  5%|▌         | 10/200 [00:36<10:54,  3.44s/it]

Crawl data 208324243 success!

  6%|▌         | 11/200 [00:39<10:52,  3.45s/it]

Crawl data 277013723 success!

  6%|▌         | 12/200 [00:42<10:00,  3.20s/it]

Crawl data 273659336 success!

  6%|▋         | 13/200 [00:43<08:21,  2.68s/it]

Crawl data 273659296 success!

  7%|▋         | 14/200 [00:46<08:39,  2.79s/it]

Crawl data 276287244 success!

  8%|▊         | 15/200 [00:48<08:02,  2.61s/it]

Crawl data 80789610 success!

  8%|▊         | 16/200 [00:52<09:24,  3.07s/it]

Crawl data 277375839 success!

  8%|▊         | 17/200 [00:57<10:38,  3.49s/it]

Crawl data 277375870 success!

  9%|▉         | 18/200 [01:02<12:00,  3.96s/it]

Crawl data 193889750 success!

 10%|▉         | 19/200 [01:04<10:02,  3.33s/it]

Crawl data 200763560 success!

 10%|█         | 20/200 [01:06<08:39,  2.88s/it]

Crawl data 273637297 success!

 10%|█         | 21/200 [01:10<09:49,  3.29s/it]

Crawl data 273795276 success!

 11%|█         | 22/200 [01:12<08:31,  2.87s/it]

Crawl data 273620894 success!

 12%|█▏        | 23/200 [01:15<08:26,  2.86s/it]

Crawl data 273795291 success!

 12%|█▏        | 24/200 [01:17<08:05,  2.76s/it]

Crawl data 263093204 success!

 12%|█▎        | 25/200 [01:20<08:30,  2.92s/it]

Crawl data 155751830 success!

 13%|█▎        | 26/200 [01:24<09:07,  3.15s/it]

Crawl data 184758720 success!

 14%|█▎        | 27/200 [01:27<08:43,  3.03s/it]

Crawl data 273442610 success!

 14%|█▍        | 28/200 [01:31<09:43,  3.39s/it]

Crawl data 263093240 success!

 14%|█▍        | 29/200 [01:34<09:05,  3.19s/it]

Crawl data 273637119 success!

 15%|█▌        | 30/200 [01:35<07:34,  2.67s/it]

Crawl data 273679403 success!

 16%|█▌        | 31/200 [01:40<09:37,  3.42s/it]

Crawl data 273702857 success!

 16%|█▌        | 32/200 [01:44<09:14,  3.30s/it]

Crawl data 273807111 success!

 16%|█▋        | 33/200 [01:48<10:27,  3.76s/it]

Crawl data 273679385 success!

 17%|█▋        | 34/200 [01:51<09:26,  3.41s/it]

Crawl data 273787788 success!

 18%|█▊        | 35/200 [01:55<10:14,  3.73s/it]

Crawl data 96835032 success!

 18%|█▊        | 36/200 [02:00<10:51,  3.97s/it]

Crawl data 273820938 success!

 18%|█▊        | 37/200 [02:05<11:52,  4.37s/it]

Crawl data 273804988 success!

 19%|█▉        | 38/200 [02:08<10:10,  3.77s/it]

Crawl data 263103233 success!

 20%|█▉        | 39/200 [02:11<09:25,  3.51s/it]

Crawl data 274358181 success!

 20%|██        | 40/200 [02:14<09:33,  3.58s/it]

Crawl data 273850400 success!

 20%|██        | 41/200 [02:17<08:49,  3.33s/it]

Crawl data 116296537 success!

 21%|██        | 42/200 [02:19<07:26,  2.83s/it]

Crawl data 273873891 success!

 22%|██▏       | 43/200 [02:23<08:42,  3.33s/it]

Crawl data 116298542 success!

 22%|██▏       | 44/200 [02:26<08:10,  3.15s/it]

Crawl data 274428979 success!

 22%|██▎       | 45/200 [02:31<09:33,  3.70s/it]

Crawl data 274429007 success!

 23%|██▎       | 46/200 [02:35<09:32,  3.72s/it]

Crawl data 181247134 success!

 24%|██▎       | 47/200 [02:39<09:56,  3.90s/it]

Crawl data 2683363 success!

 24%|██▍       | 48/200 [02:43<09:47,  3.86s/it]

Crawl data 274357872 success!

 24%|██▍       | 49/200 [02:46<09:20,  3.71s/it]

Crawl data 273371724 success!

 25%|██▌       | 50/200 [02:49<08:54,  3.56s/it]

Crawl data 112957227 success!

 26%|██▌       | 51/200 [02:54<09:59,  4.03s/it]

Crawl data 1991785 success!

 26%|██▌       | 52/200 [02:56<08:00,  3.25s/it]

Crawl data 154274984 success!

 26%|██▋       | 53/200 [03:00<08:46,  3.58s/it]

Crawl data 273468171 success!

 27%|██▋       | 54/200 [03:02<07:16,  2.99s/it]

Crawl data 16862053 success!

 28%|██▊       | 55/200 [03:04<06:42,  2.77s/it]

Crawl data 165189410 success!

 28%|██▊       | 56/200 [03:07<07:03,  2.94s/it]

Crawl data 11776869 success!

 28%|██▊       | 57/200 [03:10<06:50,  2.87s/it]

Crawl data 38161191 success!

 29%|██▉       | 58/200 [03:13<06:38,  2.80s/it]

Crawl data 72216684 success!

 30%|██▉       | 59/200 [03:17<07:56,  3.38s/it]

Crawl data 38160273 success!

 30%|███       | 60/200 [03:22<08:56,  3.83s/it]

Crawl data 54828755 success!

 30%|███       | 61/200 [03:24<07:16,  3.14s/it]

Crawl data 116295851 success!

 31%|███       | 62/200 [03:26<06:41,  2.91s/it]

Crawl data 275929133 success!

 32%|███▏      | 63/200 [03:31<08:10,  3.58s/it]

Crawl data 116298169 success!

 32%|███▏      | 64/200 [03:33<06:56,  3.06s/it]

Crawl data 116018023 success!

 32%|███▎      | 65/200 [03:38<08:13,  3.66s/it]

Crawl data 274345536 success!

 33%|███▎      | 66/200 [03:40<07:10,  3.21s/it]

Crawl data 42424845 success!

 34%|███▎      | 67/200 [03:45<07:48,  3.52s/it]

Crawl data 271392620 success!

 34%|███▍      | 68/200 [03:48<07:21,  3.35s/it]

Crawl data 205617783 success!

 34%|███▍      | 69/200 [03:51<07:28,  3.42s/it]

Crawl data 116018988 success!

 35%|███▌      | 70/200 [03:54<06:50,  3.16s/it]

Crawl data 68373476 success!

 36%|███▌      | 71/200 [03:55<05:48,  2.70s/it]

Crawl data 272618604 success!

 36%|███▌      | 72/200 [04:00<06:37,  3.11s/it]

Crawl data 120048998 success!

 36%|███▋      | 73/200 [04:02<06:10,  2.92s/it]

Crawl data 116296025 success!

 37%|███▋      | 74/200 [04:05<06:29,  3.10s/it]

Crawl data 129233346 success!

 38%|███▊      | 75/200 [04:09<06:58,  3.35s/it]

Crawl data 57734293 success!

 38%|███▊      | 76/200 [04:13<07:01,  3.40s/it]

Crawl data 272619741 success!

 38%|███▊      | 77/200 [04:18<07:59,  3.90s/it]

Crawl data 274256903 success!

 39%|███▉      | 78/200 [04:21<07:11,  3.54s/it]

Crawl data 130398871 success!

 40%|███▉      | 79/200 [04:23<06:37,  3.28s/it]

Crawl data 1742025 success!

 40%|████      | 80/200 [04:29<07:43,  3.87s/it]

Crawl data 126507339 success!

 40%|████      | 81/200 [04:32<07:18,  3.68s/it]

Crawl data 72222261 success!

 41%|████      | 82/200 [04:36<07:31,  3.83s/it]

Crawl data 274347493 success!

 42%|████▏     | 83/200 [04:41<08:14,  4.23s/it]

Crawl data 76443241 success!

 42%|████▏     | 84/200 [04:45<08:07,  4.20s/it]

Crawl data 262520301 success!

 42%|████▎     | 85/200 [04:50<08:08,  4.25s/it]

Crawl data 276113601 success!

 43%|████▎     | 86/200 [04:51<06:30,  3.43s/it]

Crawl data 276178940 success!

 44%|████▎     | 87/200 [04:54<05:58,  3.18s/it]

Crawl data 5815761 success!

 44%|████▍     | 88/200 [04:56<05:16,  2.82s/it]

Crawl data 274200674 success!

 44%|████▍     | 89/200 [04:58<04:53,  2.64s/it]

Crawl data 272618073 success!

 45%|████▌     | 90/200 [05:02<05:23,  2.94s/it]

Crawl data 276008215 success!

 46%|████▌     | 91/200 [05:04<05:12,  2.87s/it]

Crawl data 217426433 success!

 46%|████▌     | 92/200 [05:09<06:20,  3.53s/it]

Crawl data 276008111 success!

 46%|████▋     | 93/200 [05:13<06:14,  3.50s/it]

Crawl data 276006183 success!

 47%|████▋     | 94/200 [05:15<05:43,  3.24s/it]

Crawl data 275293599 success!

 48%|████▊     | 95/200 [05:17<04:46,  2.73s/it]

Crawl data 68065469 success!

 48%|████▊     | 96/200 [05:19<04:08,  2.39s/it]

Crawl data 72309207 success!

 48%|████▊     | 97/200 [05:23<04:59,  2.90s/it]

Crawl data 274070016 success!

 49%|████▉     | 98/200 [05:25<04:32,  2.67s/it]

Crawl data 262796010 success!

 50%|████▉     | 99/200 [05:29<05:09,  3.07s/it]

Crawl data 247956370 success!

 50%|█████     | 100/200 [05:32<05:01,  3.02s/it]

Crawl data 273861366 success!

 50%|█████     | 101/200 [05:34<04:48,  2.92s/it]

Crawl data 163928160 success!

 51%|█████     | 102/200 [05:40<05:49,  3.57s/it]

Crawl data 73223447 success!

 52%|█████▏    | 103/200 [05:43<05:39,  3.50s/it]

Crawl data 276006462 success!

 52%|█████▏    | 104/200 [05:47<06:05,  3.81s/it]

Crawl data 271388823 success!

 52%|█████▎    | 105/200 [05:51<05:47,  3.66s/it]

Crawl data 274223807 success!

 53%|█████▎    | 106/200 [05:54<05:22,  3.43s/it]

Crawl data 170638452 success!

 54%|█████▎    | 107/200 [05:59<06:03,  3.91s/it]

Crawl data 274256921 success!

 54%|█████▍    | 108/200 [06:01<05:19,  3.48s/it]

Crawl data 272362226 success!

 55%|█████▍    | 109/200 [06:03<04:41,  3.09s/it]

Crawl data 2001819 success!

 55%|█████▌    | 110/200 [06:05<04:08,  2.76s/it]

Crawl data 252261843 success!

 56%|█████▌    | 111/200 [06:07<03:50,  2.59s/it]

Crawl data 274253808 success!

 56%|█████▌    | 112/200 [06:11<04:07,  2.81s/it]

Crawl data 274256927 success!

 56%|█████▋    | 113/200 [06:14<04:08,  2.85s/it]

Crawl data 274069981 success!

 57%|█████▋    | 114/200 [06:15<03:36,  2.52s/it]

Crawl data 274069973 success!

 57%|█████▊    | 115/200 [06:17<03:13,  2.28s/it]

Crawl data 276800660 success!

 58%|█████▊    | 116/200 [06:21<03:39,  2.61s/it]

Crawl data 199542863 success!

 58%|█████▊    | 117/200 [06:26<04:36,  3.33s/it]

Crawl data 277284190 success!

 59%|█████▉    | 118/200 [06:28<04:11,  3.06s/it]

Crawl data 195313644 success!

 60%|█████▉    | 119/200 [06:30<03:41,  2.74s/it]

Crawl data 184888684 success!

 60%|██████    | 120/200 [06:32<03:17,  2.47s/it]

Crawl data 274256901 success!

 60%|██████    | 121/200 [06:35<03:42,  2.81s/it]

Crawl data 274347242 success!

 61%|██████    | 122/200 [06:37<03:14,  2.49s/it]

Crawl data 274070058 success!

 62%|██████▏   | 123/200 [06:40<03:19,  2.59s/it]

Crawl data 273767192 success!

 62%|██████▏   | 124/200 [06:43<03:16,  2.59s/it]

Crawl data 274070205 success!

 62%|██████▎   | 125/200 [06:45<03:12,  2.56s/it]

Crawl data 274070036 success!

 63%|██████▎   | 126/200 [06:48<03:07,  2.53s/it]

Crawl data 2525605 success!

 64%|██████▎   | 127/200 [06:51<03:33,  2.93s/it]

Crawl data 276007608 success!

 64%|██████▍   | 128/200 [06:54<03:19,  2.77s/it]

Crawl data 277283892 success!

 64%|██████▍   | 129/200 [06:58<03:37,  3.07s/it]

Crawl data 273762403 success!

 65%|██████▌   | 130/200 [07:00<03:23,  2.91s/it]

Crawl data 72308986 success!

 66%|██████▌   | 131/200 [07:02<02:52,  2.50s/it]

Crawl data 274070080 success!

 66%|██████▌   | 132/200 [07:07<03:45,  3.31s/it]

Crawl data 273860918 success!

 66%|██████▋   | 133/200 [07:12<04:18,  3.86s/it]

Crawl data 167382264 success!

 67%|██████▋   | 134/200 [07:15<04:05,  3.72s/it]

Crawl data 274256897 success!

 68%|██████▊   | 135/200 [07:18<03:30,  3.24s/it]

Crawl data 274258503 success!

 68%|██████▊   | 136/200 [07:22<03:46,  3.54s/it]

Crawl data 208913527 success!

 68%|██████▊   | 137/200 [07:24<03:19,  3.16s/it]

Crawl data 205224896 success!

 69%|██████▉   | 138/200 [07:27<03:05,  3.00s/it]

Crawl data 210138611 success!

 70%|██████▉   | 139/200 [07:28<02:36,  2.56s/it]

Crawl data 274242737 success!

 70%|███████   | 140/200 [07:32<02:58,  2.98s/it]

Crawl data 23611674 success!

 70%|███████   | 141/200 [07:37<03:20,  3.39s/it]

Crawl data 168704944 success!

 71%|███████   | 142/200 [07:40<03:20,  3.46s/it]

Crawl data 76125664 success!

 72%|███████▏  | 143/200 [07:44<03:15,  3.44s/it]

Crawl data 76022056 success!

 72%|███████▏  | 144/200 [07:45<02:44,  2.93s/it]

Crawl data 158868257 success!

 72%|███████▎  | 145/200 [07:47<02:23,  2.61s/it]

Crawl data 271245599 success!

 73%|███████▎  | 146/200 [07:51<02:33,  2.85s/it]

Crawl data 155550598 success!

 74%|███████▎  | 147/200 [07:53<02:32,  2.87s/it]

Crawl data 274080055 success!

 74%|███████▍  | 148/200 [07:57<02:45,  3.18s/it]

Crawl data 273834496 success!

 74%|███████▍  | 149/200 [08:02<03:11,  3.76s/it]

Crawl data 170693358 success!

 75%|███████▌  | 150/200 [08:08<03:29,  4.19s/it]

Crawl data 45469497 success!

 76%|███████▌  | 151/200 [08:11<03:12,  3.92s/it]

Crawl data 274234177 success!

 76%|███████▌  | 152/200 [08:16<03:21,  4.20s/it]

Crawl data 247958741 success!

 76%|███████▋  | 153/200 [08:20<03:21,  4.29s/it]

Crawl data 274256923 success!

 77%|███████▋  | 154/200 [08:22<02:43,  3.55s/it]

Crawl data 246160702 success!

 78%|███████▊  | 155/200 [08:23<02:09,  2.88s/it]

Crawl data 191808552 success!

 78%|███████▊  | 156/200 [08:26<02:08,  2.92s/it]

Crawl data 274932464 success!

 78%|███████▊  | 157/200 [08:32<02:33,  3.56s/it]

Crawl data 274256911 success!

 79%|███████▉  | 158/200 [08:37<02:48,  4.01s/it]

Crawl data 273788041 success!

 80%|███████▉  | 159/200 [08:39<02:29,  3.65s/it]

Crawl data 18011202 success!

 80%|████████  | 160/200 [08:42<02:17,  3.45s/it]

Crawl data 262864439 success!

 80%|████████  | 161/200 [08:46<02:22,  3.65s/it]

Crawl data 199041154 success!

 81%|████████  | 162/200 [08:49<02:00,  3.18s/it]

Crawl data 274256917 success!

 82%|████████▏ | 163/200 [08:52<01:58,  3.20s/it]

Crawl data 177617351 success!

 82%|████████▏ | 164/200 [08:57<02:14,  3.75s/it]

Crawl data 182849278 success!

 82%|████████▎ | 165/200 [09:01<02:14,  3.83s/it]

Crawl data 247061483 success!

 83%|████████▎ | 166/200 [09:06<02:19,  4.10s/it]

Crawl data 276661348 success!

 84%|████████▎ | 167/200 [09:10<02:21,  4.30s/it]

Crawl data 262863364 success!

 84%|████████▍ | 168/200 [09:13<02:04,  3.88s/it]

Crawl data 276353075 success!

 84%|████████▍ | 169/200 [09:17<01:55,  3.74s/it]

Crawl data 276371086 success!

 85%|████████▌ | 170/200 [09:21<01:56,  3.90s/it]

Crawl data 31648264 success!

 86%|████████▌ | 171/200 [09:25<01:57,  4.06s/it]

Crawl data 176757178 success!

 86%|████████▌ | 172/200 [09:28<01:43,  3.71s/it]

Crawl data 276824221 success!

 86%|████████▋ | 173/200 [09:30<01:26,  3.22s/it]

Crawl data 274252492 success!

 87%|████████▋ | 174/200 [09:34<01:29,  3.44s/it]

Crawl data 277173291 success!

 88%|████████▊ | 175/200 [09:37<01:17,  3.11s/it]

Crawl data 167170706 success!

 88%|████████▊ | 176/200 [09:40<01:16,  3.20s/it]

Crawl data 609959 success!

 88%|████████▊ | 177/200 [09:45<01:23,  3.63s/it]

Crawl data 1524363 success!

 89%|████████▉ | 178/200 [09:48<01:18,  3.58s/it]

Crawl data 101044184 success!

 90%|████████▉ | 179/200 [09:52<01:15,  3.59s/it]

Crawl data 19253377 success!

 90%|█████████ | 180/200 [09:55<01:07,  3.39s/it]

Crawl data 199268671 success!

 90%|█████████ | 181/200 [09:57<01:00,  3.21s/it]

Crawl data 276327744 success!

 91%|█████████ | 182/200 [09:59<00:51,  2.84s/it]

Crawl data 274381304 success!

 92%|█████████▏| 183/200 [10:02<00:45,  2.69s/it]

Crawl data 6498455 success!

 92%|█████████▏| 184/200 [10:04<00:43,  2.69s/it]

Crawl data 52789105 success!

 92%|█████████▎| 185/200 [10:09<00:46,  3.11s/it]

Crawl data 272406020 success!

 93%|█████████▎| 186/200 [10:11<00:41,  2.99s/it]

Crawl data 199172796 success!

 94%|█████████▎| 187/200 [10:14<00:37,  2.87s/it]

Crawl data 201623929 success!

 94%|█████████▍| 188/200 [10:16<00:33,  2.77s/it]

Crawl data 273804345 success!

 94%|█████████▍| 189/200 [10:18<00:25,  2.33s/it]

Crawl data 274256905 success!

 95%|█████████▌| 190/200 [10:22<00:29,  2.97s/it]

Crawl data 271389476 success!

 96%|█████████▌| 191/200 [10:25<00:25,  2.83s/it]

Crawl data 199969338 success!

 96%|█████████▌| 192/200 [10:27<00:21,  2.65s/it]

Crawl data 193586399 success!

 96%|█████████▋| 193/200 [10:28<00:15,  2.28s/it]

Crawl data 249700534 success!

 97%|█████████▋| 194/200 [10:31<00:14,  2.48s/it]

Crawl data 177005939 success!

 98%|█████████▊| 195/200 [10:36<00:16,  3.21s/it]

Crawl data 274996607 success!

 98%|█████████▊| 196/200 [10:41<00:15,  3.79s/it]

Crawl data 194568564 success!

 98%|█████████▊| 197/200 [10:46<00:11,  3.99s/it]

Crawl data 276918065 success!

 99%|█████████▉| 198/200 [10:51<00:08,  4.22s/it]

Crawl data 276475452 success!

100%|█████████▉| 199/200 [10:54<00:03,  3.97s/it]

Crawl data 242265656 success!

100%|██████████| 200/200 [10:57<00:00,  3.29s/it]

Done! Data saved to boots.csv

In [22]:
df = pd.read_csv(r'C:\Users\leebo\OneDrive\Documents\internTMA\TMA_Internship_DE_Project\crawl_tiki_API\giay_sandal.csv')

In [23]:
df.head(15)

,Product_ID,Product_name,Description,brand_name,price
0,52228079,Giày Sandal Nữ BIGGBEN Da Bò Thật SDN51,Sandal Nữ với chất liệu da bò bền đẹp kết hợp ...,BIGGBEN,329000
1,177772556,"Giày sandal nữ BIGGBEN cao 4,5cm SDN75",Chất Liệu :Da tổng hợpKích Thước :từ 35 đến 40...,BIGGBEN,349000
2,171201432,Giày sandal nữ dây Giavy SK109,GIÀY QUAI HẬU NỮ Thương hiệu độc quyề...,GIAVY,195000
3,153010212,Giày sandal nữ dây Giavy SK109,GIÀY QUAI HẬU NỮ Thương hiệu độc quyề...,GIAVY,195000
4,42737212,Giày sandal nữ TLG 20799-1,Giày sandal nữ TLG 20799-1 với thiết kế trẻ tr...,TLG Thành Long,150200
5,153010553,Giày sandal dây nữ Giavy SK377,GIÀY QUAI HẬU NỮ Thương hiệu độc quyền : G...,GIAVY,195000
6,42737104,Giày sandal nữ TLG 20615-8,Giày sandal nữ TLG 20615-8 với thiết kế trẻ tr...,TLG Thành Long,150200
7,112958887,giầy sandal nữ thời trang sành điệu 21828,*) THÔNG TIN SẢN PHẨM • ✦ Giày nữ đẹp...,ĐỒ DA THÀNH LONG TLG,150000
8,276670235,Giày sandal quai ngang 1F PN15018,Giày sandal quai ngang 1F PN15018---------- 1...,PABNO,285000
9,42737023,Giày sandal nữ TLG 20716-5,Giày sandal nữ TLG 20716-5 với thiết kế trẻ tr...,TLG Thành Long,150200
10,276098515,Giày Sandal Nữ Da Bò Thật BIGGBEN Cao Cấp SDN107,Thương hiệu: BIGBENChất Liệu :Da bò thật 100%K...,BIGGBEN,299000
11,59209381,Giày Sandal Nữ BIGGBEN Da Bò Thật SDN54,Sandal Nữ với chất liệu da bò bền đẹp kết hợp ...,BIGGBEN,279000
12,112827241,Giày sandal nữ phong cách thời thượng 21823,*) THÔNG TIN SẢN PHẨM • ✦ Giày nữ đẹp...,ĐỒ DA THÀNH LONG TLG,170500
13,177772693,"Giày sandal nữ BIGGBEN cao 4,5cm SDN76",Chất Liệu :Da tổng hợpKích Thước :từ 35 đến 40...,BIGGBEN,349000
14,23166857,Giày Sandal Nữ BIGGBEN Da Bò Thật SDN33,Được làm Bằng chất liệu Da Bò Thật 100% .Sand...,BIGGBEN,329000

# thêm dữ liệu cho bảng Product

In [ ]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

# Kết nối đến MySQL
DATABASE_URL = "mysql+pymysql://myuser:mypassword@localhost:3306/mydatabase"
engine = create_engine(DATABASE_URL)

# Đọc dữ liệu từ file CSV
df = pd.read_csv(r"C:\Users\leebo\OneDrive\Documents\internTMA\TMA_Internship_DE_Project\crawl_tiki_API\giay_the_thao.csv")

# Đổi tên cột theo bảng MySQL
df = df.rename(columns={
    'Product_ID': 'ProductID',
    'Product_name': 'Name',
    'brand_name': 'Brand',
    'price': 'Price'
})

# Thêm cột 'Category' mặc định là NULL
df['Category'] = None  

# Gán giá trị ngẫu nhiên cho cột 'Size'
size_options = [39, 40, 41]
df['Size'] = np.random.choice(size_options, size=len(df))

# Cập nhật ProductID bằng cách nối thêm "G" + Size
df['ProductID'] = df['ProductID'].astype(str) + "G" + df['Size'].astype(str)

# Chuẩn hóa dữ liệu (chuyển về chữ thường để tránh lỗi so khớp)
df['Name'] = df['Name'].str.lower().str.strip()

# Điều kiện gán giá trị cho cột 'Category'
def assign_category(name):
    if "boot" in name or "bốt" in name:
        if "nam" in name:
            return "GT01"
        elif "nữ" in name:
            return "GT02"
        else:
            return np.random.choice(["GT01", "GT02"])
    elif "giày thể thao" in name:
        if "nam" in name:
            return "GTT01"
        elif "nữ" in name:
            return "GTT02"
        else:
            return np.random.choice(["GTT01", "GTT02"])
    elif "sandal" in name:
        if "nam" in name:
            return "GSD01"
        elif "nữ" in name:
            return "GSD02"
        else:
            return np.random.choice(["GSD01", "GSD02"])
    return None

# Áp dụng function cho cột 'Category'
df['Category'] = df['Name'].apply(assign_category)

# Chỉ giữ các cột khớp với bảng Product
df = df[['ProductID', 'Name', 'Category', 'Description', 'Brand', 'Price', 'Size']]

# Đổ dữ liệu vào bảng Product trong MySQL
df.to_sql("Product", con=engine, if_exists="append", index=False, chunksize=1000)

print("Dữ liệu đã được đổ vào bảng Product thành công!")

Dữ liệu đã được đổ vào bảng Product thành công!

In [7]:
DATABASE_URL = "mysql+pymysql://myuser:mypassword@localhost:3306/mydatabase"
engine = create_engine(DATABASE_URL)

# Truy vấn dữ liệu từ bảng Product
query = "SELECT * FROM Product"
df = pd.read_sql(query, con=engine)

# Lưu vào file CSV
df.to_csv("Product.csv", index=False, encoding='utf-8-sig')

print("Dữ liệu đã được lưu vào Product.csv thành công!")

Dữ liệu đã được lưu vào Product.csv thành công!

# thêm dữ liệu cho bảng Promotion

In [ ]:
import pandas as pd
import random
from faker import Faker
from datetime import timedelta
from sqlalchemy import create_engine, Integer

# Khởi tạo Faker
fake = Faker()

# Kết nối MySQL
DATABASE_URL = "mysql+pymysql://myuser:mypassword@localhost:3306/mydatabase"
engine = create_engine(DATABASE_URL)

# Lấy danh sách ProductID từ bảng Product
query_product = "SELECT ProductID FROM Product"
df_product = pd.read_sql(query_product, engine)

# Lấy danh sách PlatformID từ bảng Platform
query_platform = "SELECT ID FROM Platform"
df_platform = pd.read_sql(query_platform, engine)

# Chuyển sang danh sách (hoặc để trống nếu không có dữ liệu)
product_ids = df_product['ProductID'].tolist() if not df_product.empty else [None]
platform_ids = df_platform['ID'].tolist() if not df_platform.empty else [None]

# Tạo dữ liệu giả cho bảng Promotion
data = []
existing_ids = set()  # Để đảm bảo ID không trùng lặp

for _ in range(100):  # Sinh 100 dòng giả lập
    while True:
        promo_id = random.randint(10000000, 99999999)  # Tạo mã 8 chữ số ngẫu nhiên
        if promo_id not in existing_ids:  # Đảm bảo ID không trùng
            existing_ids.add(promo_id)
            break

    product_id = random.choice(product_ids)
    discount_rate = round(random.uniform(5, 50), 2)  # Giảm giá từ 5% đến 50%
    start_date = fake.date_between(start_date="-1y", end_date="today")  # Ngẫu nhiên trong 1 năm gần đây
    end_date = start_date + timedelta(days=random.randint(7, 30))  # Khuyến mãi kéo dài 7 - 30 ngày
    platform_id = random.choice(platform_ids)
    promo_name = fake.sentence(nb_words=3)  # Tên chương trình khuyến mãi ngắn

    data.append([promo_id, promo_name, product_id, discount_rate, start_date, end_date, platform_id])

# Chuyển thành DataFrame
df = pd.DataFrame(data, columns=["ID", "PromoName", "ProductID", "Discount_rate", "DateStart", "DateEnd", "PlatformID"])

# # Ghi dữ liệu vào MySQL với kiểu dữ liệu đúng
# df.to_sql("Promotion", con=engine, if_exists="append", index=False, chunksize=1000, dtype={"ID": Integer})

# print("✅ Dữ liệu giả đã được thêm vào bảng Promotion thành công!")

In [9]:
df

,ID,PromoName,ProductID,Discount_rate,DateStart,DateEnd,PlatformID
0,49592333,Make anyone past model.,275851525G41,27.39,2024-03-21,2024-04-13,None
1,11274816,Example pretty worry.,274253808G41,30.38,2024-03-27,2024-04-17,None
2,92432998,Paper.,263103233G40,48.90,2024-06-16,2024-07-05,None
3,16872674,Relationship enough.,23611674G39,7.44,2024-04-21,2024-05-06,None
4,44317685,Give.,66566234G40,17.19,2024-12-06,2024-12-14,None
...,...,...,...,...,...,...,...
95,48078534,Condition measure eat.,206952681G41,22.88,2024-07-08,2024-08-07,None
96,50501629,Set history buy.,21060817G40,19.33,2024-04-23,2024-05-23,None
97,70386213,Form box.,276113601G39,28.63,2024-06-29,2024-07-20,None
98,57941842,Similar million.,274046223G39,48.34,2025-01-31,2025-02-22,None
99,28910250,Economy address.,57734293G40,41.83,2024-05-16,2024-05-25,None

# Dữ liệu Customer

In [35]:
from faker import Faker
import pandas as pd
import random
from datetime import datetime

# Số lượng khách hàng giả lập
fake_V = Faker('vi_VN')
num_customers = 50

# Tạo dữ liệu giả
customers = []
for i in range(num_customers):
    customer_id = f"KH{i+1:03d}"
    name = fake_V.name()
    gender = random.choice(['male', 'female', 'other'])
    dob = fake_V.date_of_birth(minimum_age=18, maximum_age=60)
    phone = ''.join(filter(str.isdigit, fake_V.phone_number()))  # Loại bỏ ký tự không phải số
    address = fake_V.address().split("\n")[0]  # Chỉ lấy dòng đầu tiên
    location_id = random.randint(1, 40)
    
    customers.append((customer_id, name, gender, dob, phone, address, location_id))

# Tạo DataFrame
df_customers = pd.DataFrame(customers, columns=["Customer_ID", "Name", "Gender", "Date_of_Birth", "Phone", "Address", "Location_ID"])

# Chuyển Date_of_Birth sang datetime
df_customers['Date_of_Birth'] = pd.to_datetime(df_customers['Date_of_Birth'])

# Tính tuổi chính xác
current_year = datetime.now().year
df_customers['Age'] = current_year - df_customers['Date_of_Birth'].dt.year

# Hiển thị 5 dòng đầu
print(df_customers.head())

  Customer_ID             Name  Gender Date_of_Birth        Phone  \
0       KH001  Hưng Trí Nguyễn  female    1982-10-31  84960053730
1       KH002         Hà Dương  female    1968-10-27  84296692968
2       KH003       Khoa Hoàng   other    1990-11-09   8448503078
3       KH004         Quang Lê  female    1974-09-05    066685765
4       KH005   Huy Xuân Hoàng  female    1973-09-12   8422453170

           Address  Location_ID  Age
0       6 Jane Hẻm           16   43
1       12 John Tổ            7   57
2  99 Nguyễn Đường           15   35
3    23 Jane Đường           39   51
4         7 Vũ Khu           26   52

In [40]:
from sqlalchemy import create_engine
import pandas as pd

# Thông tin kết nối MySQL
DB_USER = 'myuser'        # Thay bằng user của bạn
DB_PASSWORD = 'mypassword'  # Thay bằng password của bạn
DB_HOST = 'localhost'   # Hoặc IP của server
DB_PORT = '3306'        # Cổng mặc định của MySQL
DB_NAME = 'mydatabase' # Tên database chứa bảng customers

# Kết nối với MySQL
engine = create_engine(f"mysql+pymysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}")

In [43]:
# Đổi tên cột để khớp với bảng MySQL
df_customers = df_customers.rename(columns={
    "Customer_ID": "ID",
    "Date_of_Birth": "DOB",
    "Phone": "phoneNumber",
    "Location_ID": "locationID"
})

In [ ]:
df_customers = df_customers[['ID', 'Name', 'Gender', 'Age', 'DOB', 'phoneNumber', 'Address', 'locationID']]

In [50]:
df_customers.head()

,ID,Name,Gender,Age,DOB,phoneNumber,Address,locationID
0,KH001,Hưng Trí Nguyễn,female,43,1982-10-31,84960053730,6 Jane Hẻm,16
1,KH002,Hà Dương,female,57,1968-10-27,84296692968,12 John Tổ,7
2,KH003,Khoa Hoàng,other,35,1990-11-09,8448503078,99 Nguyễn Đường,15
3,KH004,Quang Lê,female,51,1974-09-05,066685765,23 Jane Đường,39
4,KH005,Huy Xuân Hoàng,female,52,1973-09-12,8422453170,7 Vũ Khu,26

In [55]:
import pandas as pd
import pymysql
from sqlalchemy import create_engine

# Thông tin kết nối MySQL
host = "localhost"
port = 3306
user = "myuser"
password = "mypassword"
database = "mydatabase"

# Tạo engine kết nối MySQL
engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}")

# Lấy danh sách locationID từ bảng Location
query = "SELECT ID FROM Location"
existing_locations = pd.read_sql(query, con=engine)["ID"].tolist()

# Lọc ra các locationID chưa có trong bảng Location
new_locations = df_customers[~df_customers["locationID"].isin(existing_locations)]["locationID"].unique()

# Thêm các locationID mới vào bảng Location (giả sử chỉ có ID, không có tên)
if len(new_locations) > 0:
    df_new_locations = pd.DataFrame(new_locations, columns=["ID"])
    df_new_locations.to_sql("Location", con=engine, if_exists="append", index=False)
    print(f"✅ Đã thêm {len(new_locations)} locationID mới vào bảng Location.")
else:
    print("✅ Tất cả locationID đã tồn tại trong bảng Location.")

# Đẩy dữ liệu vào bảng Customer
df_customers.to_sql("Customer", con=engine, if_exists="append", index=False)

print("✅ Dữ liệu đã được đẩy vào bảng Customer thành công!")

✅ Đã thêm 30 locationID mới vào bảng Location.
✅ Dữ liệu đã được đẩy vào bảng Customer thành công!

# thêm dữ liệu cho cột AppliedPromotion

In [2]:
import random
from sqlalchemy import create_engine, text

# Kết nối đến MySQL
DATABASE_URL = "mysql+pymysql://myuser:mypassword@127.0.0.1:3306/mydatabase"
engine = create_engine(DATABASE_URL)

# Kết nối & thực hiện truy vấn
with engine.connect() as conn:
    # 🔹 Lấy danh sách PromotionID từ bảng Promotion
    promotion_ids = conn.execute(text("SELECT ID FROM Promotion")).fetchall()
    promotion_ids = [row[0] for row in promotion_ids]

    # 🔹 Lấy danh sách CustomerID từ bảng Customer
    customer_ids = conn.execute(text("SELECT ID FROM Customer")).fetchall()
    customer_ids = [row[0] for row in customer_ids]

    # 🔍 Kiểm tra dữ liệu
    if not promotion_ids or not customer_ids:
        print("❌ Không có dữ liệu trong bảng Promotion hoặc Customer!")
    else:
        # 🔥 Chèn dữ liệu giả lập vào AppliedPromotion
        for _ in range(10):
            applied_promotion_id = random.randint(10_000_000, 99_999_999)  # ID 7-8 chữ số
            promotion_id = random.choice(promotion_ids)  # Chọn PromotionID ngẫu nhiên
            customer_id = random.choice(customer_ids)  # Chọn CustomerID ngẫu nhiên

            sql = text("INSERT INTO AppliedPromotion (ID, PromotionID, CustomerID) VALUES (:id, :promo, :cust)")
            values = {"id": applied_promotion_id, "promo": promotion_id, "cust": customer_id}

            conn.execute(sql, values)

        # ✅ Lưu thay đổi
        conn.commit()
        print("✅ Dữ liệu đã được chèn thành công!")

✅ Dữ liệu đã được chèn thành công!

# thêm dữ liệu cho Shipping

In [4]:
import pandas as pd
from faker import Faker
import random

fake = Faker()

# Giả sử danh sách OrderID từ bảng Order (có thể rỗng hoặc không)
existing_order_ids = [f"DH{str(i).zfill(3)}" for i in range(1, 101)]  # Tạo danh sách DH001 - DH100

def generate_shipping_data(num_records):
    shipping_data = []
    for _ in range(num_records):
        # Tạo ID 9-10 chữ số
        shipping_id = random.randint(100000000, 9999999999)
        
        # Tạo Carrier (giả định là chuỗi ngẫu nhiên)
        carrier = fake.word()
        
        # Tạo OrderID: Chọn ngẫu nhiên từ danh sách nếu có, ngược lại None
        order_id = random.choice(existing_order_ids) if existing_order_ids else None
        
        # Tạo Status
        status = fake.random_element(elements=("Pending", "Shipped", "Delivered", "Cancelled"))
        
        shipping_data.append([shipping_id, carrier, order_id, status])
    
    # Chuyển danh sách thành DataFrame
    df = pd.DataFrame(shipping_data, columns=["ID", "Carrier", "OrderID", "Status"])
    return df

# Tạo DataFrame với 5 bản ghi
df_shipping = generate_shipping_data(5)

# Hiển thị DataFrame
print(df_shipping)

           ID      Carrier OrderID     Status
0  9678500180       weight   DH069    Pending
1  1950980225       arrive   DH091    Pending
2   462783670         stop   DH093  Cancelled
3  1850452935      natural   DH087  Delivered
4  5651827605  participant   DH073    Shipped

# dưới này đừng quan tâm nha ae

In [ ]:
# headers = {
#     "User-Agent": "Mozilla/5.0"
# }

def get_seller_info(seller_id):
    """Lấy thông tin người bán từ API"""
    url = f'https://api.tiki.vn/product-detail/v2/widgets/seller?seller_id={seller_id}'
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        seller_data = response.json().get('data', {}).get('seller', {})
        return {
            'seller_rating': seller_data.get('avg_rating_point'),
            'review_count': seller_data.get('review_count'),
            'url_seller': seller_data.get('url')
        }
    return {'seller_rating': None, 'review_count': None, 'url_seller': None}


def parser_product(json):
    """Trích xuất thông tin sản phẩm từ API"""
    seller_id = json.get('current_seller', {}).get('id')
    seller_info = get_seller_info(seller_id) if seller_id else {'Seller Rating': None, 'review_count': None}
    
    return {
        'id': json.get('id'),
        'name': json.get('name'),
        'url_key': json.get('url_key'),
        'url_product': json.get('breadcrumbs', [{}])[-1].get('url'),
        'image_base_url': json.get('images', [{}])[0].get('base_url'),
        'rating_average': json.get('rating_average'),
        # 'review_count': json.get('review_count'),
        'quantity_sold': json.get('quantity_sold'),
        'brand_name': json.get('brand', {}).get('name'), 
        'category': [bc.get('name') for bc in json.get('breadcrumbs', [])[:-1]],
        'category_id': [bc.get('category_id') for bc in json.get('breadcrumbs', [])[:-1]],
        'current_seller': json.get('current_seller', {}).get('name'), 
        'inventory_status': json.get('inventory_status'),
        'stock_item_qty': json.get('stock_item', {}).get('qty'),
        'original_price': json.get('original_price'),
        'discount': json.get('discount'),
        'price': json.get('price'),
        
        # 'url_seller': json.get('current_seller', {}).get('link'),
        # 'Seller_Type': json.get('current_seller', {}).get('name'),
        # 'Seller_Location': json.get('current_seller', {}).get('type'),
        # 'seller_rating': seller_info['seller_rating'],
        # 'review_count': seller_info['review_count']
        'seller_rating': seller_info['seller_rating'],
        'review_count_seller': seller_info['review_count'],  # Review của người bán
        'url_seller': seller_info['url_seller'],
        'Seller_Type': json.get('current_seller', {}).get('name')
    }

# Đọc danh sách ID sản phẩm
df_id = pd.read_csv('TestID_LamDepSK.csv')
p_ids = df_id.id.to_list()
result = []

# Bắt đầu thu thập dữ liệu
for pid in tqdm(p_ids, total=len(p_ids)):
    retries = 3
    while retries > 0:
        response = requests.get(f'https://tiki.vn/api/v2/products/{pid}', headers=headers)
        
        if response.status_code == 200:
            print(f'Crawl data {pid} success!')
            result.append(parser_product(response.json()))
            break
        elif response.status_code == 429:
            print(f'Too many requests! Waiting before retrying {pid}...')
            time.sleep(random.uniform(5, 10))
        elif response.status_code == 404:
            print(f'Product {pid} not found (404). Skipping...')
            break
        else:
            print(f'Failed to fetch data for {pid}, status code: {response.status_code}')
        retries -= 1
    
    time.sleep(random.uniform(1, 5))

# Lưu dữ liệu ra file CSV
df_product = pd.DataFrame(result)
df_product.to_csv('LamDepVaSucKhoe1.csv', index=False)
print("Done! Data saved to LamDepVaSucKhoe1.csv")

# Dùng code bên dưới khi thực hiện crawl với số lượng page và dữ liệu nhiều.

In [ ]:
# from tqdm import tqdm
# from concurrent.futures import ThreadPoolExecutor, as_completed

# # Hàm parser dữ liệu sản phẩm
# def parser_product(json):
#     return {
#         'id': json.get('id'),
#         'name': json.get('name'),
#         'short_description': json.get('short_description'),
#         'price': json.get('price'),
#         'list_price': json.get('list_price'),
#         'quantity_sold': json.get('quantity_sold'),
#         'discount': json.get('discount'),
#         'discount_rate': json.get('discount_rate'),
#         'review_count': json.get('review_count'),
#         'order_count': json.get('order_count'),
#         'inventory_status': json.get('inventory_status'),
#         'is_visible': json.get('is_visible'),
#         'stock_item_qty': json.get('stock_item', {}).get('qty'),
#         'stock_item_max_sale_qty': json.get('stock_item', {}).get('max_sale_qty'),
#         'product_name': json.get('meta_title'),
#         'brand_id': json.get('brand', {}).get('id'),
#         'brand_name': json.get('brand', {}).get('name')
#     }

# # Đọc danh sách ID sản phẩm
# df_id = pd.read_csv('ID_ThoiTrangNam1.csv')
# p_ids = df_id.id.to_list()

# # Danh sách User-Agent để tránh bị chặn
# USER_AGENTS = [
#     'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36',
#     'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36',
#     'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:92.0) Gecko/20100101 Firefox/92.0'
# ]

# # Hàm gửi request lấy dữ liệu sản phẩm
# def fetch_product(pid):
#     retries = 3
#     while retries > 0:
#         headers = {'User-Agent': random.choice(USER_AGENTS)}  # Random User-Agent
#         response = requests.get(f'https://tiki.vn/api/v2/products/{pid}', headers=headers)
        
#         if response.status_code == 200:
#             if response.text.strip():  # Kiểm tra response không rỗng
#                 try:
#                     return parser_product(response.json())  
#                 except requests.JSONDecodeError:
#                     print(f'⚠️ Lỗi JSONDecodeError cho sản phẩm {pid}, response: {response.text[:200]}')
#             else:
#                 print(f'⚠️ Phản hồi rỗng cho sản phẩm {pid}')
#         elif response.status_code == 404:
#             return None  # Sản phẩm không tồn tại
#         elif response.status_code == 429:
#             wait_time = random.uniform(5, 10)
#             print(f'⚠️ Quá nhiều request (429). Đợi {wait_time:.2f}s trước khi thử lại...')
#             time.sleep(wait_time)

#         retries -= 1
#         time.sleep(random.uniform(2, 5))  # Tránh spam request

#     print(f'❌ Bỏ qua sản phẩm {pid} sau {3 - retries} lần thử')
#     return None

# # Thu thập dữ liệu đa luồng
# result = []
# max_workers = 10  # Tùy chỉnh số luồng
# with ThreadPoolExecutor(max_workers=max_workers) as executor:
#     futures = {executor.submit(fetch_product, pid): pid for pid in p_ids}
#     for future in tqdm(as_completed(futures), total=len(futures)):
#         data = future.result()
#         if data:
#             result.append(data)

# # Lưu dữ liệu ra file CSV
# df_product = pd.DataFrame(result)
# df_product.to_csv('tet.csv', index=False)
# print("✅ Done! Data saved to tet.csv")

  4%|▍         | 21/500 [00:03<01:26,  5.55it/s]

⚠️ Quá nhiều request (429). Đợi 7.25s trước khi thử lại...
⚠️ Quá nhiều request (429). Đợi 8.10s trước khi thử lại...
⚠️ Quá nhiều request (429). Đợi 8.17s trước khi thử lại...